In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

print("Environment ready")

Environment ready

In [2]:
from pathlib import Path

BASE_DIR = Path.cwd().parent

MOVIES_PATH = BASE_DIR / "data" / "raw" / "tmdb_5000_movies.csv"
CREDITS_PATH = BASE_DIR / "data" / "raw" / "tmdb_5000_credits.csv"

print("Movies:", MOVIES_PATH)
print("Credits:", CREDITS_PATH)
print("Movies exists:", MOVIES_PATH.exists())
print("Credits exists:", CREDITS_PATH.exists())

Movies: c:\Users\Win 10\Desktop\movie-recommender\data\raw\tmdb_5000_movies.csv
Credits: c:\Users\Win 10\Desktop\movie-recommender\data\raw\tmdb_5000_credits.csv
Movies exists: True
Credits exists: True

In [3]:
movies = pd.read_csv(MOVIES_PATH)
credits = pd.read_csv(CREDITS_PATH)

print("Movies shape:", movies.shape)
print("Credits shape:", credits.shape)

Movies shape: (4803, 20)
Credits shape: (4803, 4)

In [4]:
display(movies.head())

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
display(credits.head())

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
print("MOVIES COLUMNS")
print("=" * 50)

for column in movies.columns:
    print(column)

print("\nCREDITS COLUMNS")
print("=" * 50)

for column in credits.columns:
    print(column)

MOVIES COLUMNS
==================================================
budget
genres
homepage
id
keywords
original_language
original_title
overview
popularity
production_companies
production_countries
release_date
revenue
runtime
spoken_languages
status
tagline
title
vote_average
vote_count

CREDITS COLUMNS
==================================================
movie_id
title
cast
crew

In [7]:
print("Movies missing values")
display(
    movies.isnull()
    .sum()
    .sort_values(ascending=False)
    .to_frame("missing")
)

print("\nCredits missing values")
display(
    credits.isnull()
    .sum()
    .sort_values(ascending=False)
    .to_frame("missing")
)

Movies missing values

                      missing
homepage                 3091
tagline                   844
overview                    3
runtime                     2
release_date                1
id                          0
budget                      0
genres                      0
original_title              0
popularity                  0
original_language           0
keywords                    0
production_countries        0
production_companies        0
spoken_languages            0
revenue                     0
status                      0
title                       0
vote_average                0
vote_count                  0

Credits missing values

          missing
movie_id        0
title           0
cast            0
crew            0

In [8]:
print("Duplicate movie rows:", movies.duplicated().sum())
print("Duplicate credit rows:", credits.duplicated().sum())

Duplicate movie rows: 0
Duplicate credit rows: 0

In [9]:
display(movies.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
budget,4803.0,NaN,NaN,NaN,29045039.875286,40722391.25855,0.0,790000.0,15000000.0,40000000.0,380000000.0
genres,4803,1175,"[{""id"": 18, ""name"": ""Drama""}]",370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
homepage,1712,1691,http://www.thehungergames.movie/,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,4803.0,NaN,NaN,NaN,57165.484281,88694.614033,5.0,9014.5,14629.0,58610.5,459488.0
keywords,4803,4222,[],412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original_language,4803,37,en,4505,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original_title,4803,4801,Batman,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
overview,4800,4800,"In the 22nd century, a paraplegic Marine is di...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
popularity,4803.0,NaN,NaN,NaN,21.492301,31.81665,0.0,4.66807,12.921594,28.313505,875.581305
production_companies,4803,3697,[],351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
production_countries,4803,469,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_date,4802,3280,2006-01-01,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
revenue,4803.0,NaN,NaN,NaN,82260638.651676,162857100.94283,0.0,0.0,19170001.0,92917187.0,2787965087.0
runtime,4801.0,NaN,NaN,NaN,106.875859,22.611935,0.0,94.0,103.0,118.0,338.0
spoken_languages,4803,544,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",3171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,4803,3,Released,4795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tagline,3959,3944,Based on a true story.,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,4803,4800,The Host,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vote_average,4803.0,NaN,NaN,NaN,6.092172,1.194612,0.0,5.6,6.2,6.8,10.0
vote_count,4803.0,NaN,NaN,NaN,690.217989,1234.585891,0.0,54.0,235.0,737.0,13752.0

In [10]:
print("MOVIES")
print("Shape:", movies.shape)
print("Columns:")
print(movies.columns.tolist())

print("\nCREDITS")
print("Shape:", credits.shape)
print("Columns:")
print(credits.columns.tolist())

MOVIES
Shape: (4803, 20)
Columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

CREDITS
Shape: (4803, 4)
Columns:
['movie_id', 'title', 'cast', 'crew']

In [11]:
print("Movies duplicates:", movies.duplicated().sum())
print("Credits duplicates:", credits.duplicated().sum())

Movies duplicates: 0
Credits duplicates: 0

In [12]:
display(credits.head())

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
# Vérification des clés
print("Movies IDs uniques :", movies["id"].nunique())
print("Credits IDs uniques :", credits["movie_id"].nunique())

print(
    "IDs communs :",
    movies["id"].isin(credits["movie_id"]).sum()
)

Movies IDs uniques : 4803
Credits IDs uniques : 4803
IDs communs : 4803

In [14]:
# Fusion des deux datasets
df = movies.merge(
    credits,
    left_on="id",
    right_on="movie_id",
    how="inner"
)

print("Dataset fusionné :", df.shape)
display(df.head())

Dataset fusionné : (4803, 24)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
# Colonnes utiles pour le recommender
columns = [
    "id",
    "title",
    "overview",
    "genres",
    "keywords",
    "cast",
    "crew",
    "vote_average",
    "vote_count",
    "popularity",
]

df = df[columns].copy()

print("Dimensions après sélection :", df.shape)
display(df.head())

KeyError: "['title'] not in index"

In [16]:
print(df.columns.tolist())

['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average', 'vote_count', 'movie_id', 'title_y', 'cast', 'crew']

In [17]:
df = df.rename(columns={
    "title_x": "title"
})

In [18]:
df = df.drop(columns=["title_y"])

In [19]:
print("title" in df.columns)

True

In [20]:
columns = [
    "id",
    "title",
    "overview",
    "genres",
    "keywords",
    "cast",
    "crew",
    "vote_average",
    "vote_count",
    "popularity",
]

df = df[columns].copy()

print("Dimensions après sélection :", df.shape)

display(df.head())

Dimensions après sélection : (4803, 10)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,43.926995

In [21]:
print(df.columns.tolist())

['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew', 'vote_average', 'vote_count', 'popularity']

In [22]:
print("Dimensions :", df.shape)
display(df.head())

Dimensions : (4803, 10)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,43.926995

In [23]:
text_columns = [
    "overview",
    "genres",
    "keywords",
    "cast",
    "crew",
]

for column in text_columns:
    df[column] = df[column].fillna("")

print("Valeurs manquantes après nettoyage :")
display(
    df.isnull()
    .sum()
    .to_frame("missing")
)

Valeurs manquantes après nettoyage :

              missing
id                  0
title               0
overview            0
genres              0
keywords            0
cast                0
crew                0
vote_average        0
vote_count          0
popularity          0

In [24]:
PROCESSED_PATH = BASE_DIR / "data" / "processed" / "movies_clean.csv"

df.to_csv(PROCESSED_PATH, index=False)

print("✅ Dataset nettoyé sauvegardé")
print("Fichier :", PROCESSED_PATH)
print("Dimensions :", df.shape)

✅ Dataset nettoyé sauvegardé
Fichier : c:\Users\Win 10\Desktop\movie-recommender\data\processed\movies_clean.csv
Dimensions : (4803, 10)

In [25]:
import ast

def extract_names(value):
    try:
        items = ast.literal_eval(value)
        return [item["name"] for item in items]
    except (ValueError, TypeError, SyntaxError):
        return []

In [26]:
df["genres"] = df["genres"].apply(extract_names)
df["keywords"] = df["keywords"].apply(extract_names)

In [27]:
display(
    df[["title", "genres", "keywords"]].head()
)

,title,genres,keywords
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [28]:
def extract_cast(value):
    try:
        items = ast.literal_eval(value)
        return [
            item["name"]
            for item in items[:3]
        ]
    except (ValueError, TypeError, SyntaxError):
        return []

In [29]:
df["cast"] = df["cast"].apply(extract_cast)

In [30]:
def extract_director(value):
    try:
        items = ast.literal_eval(value)

        for item in items:
            if item.get("job") == "Director":
                return [item["name"]]

        return []

    except (ValueError, TypeError, SyntaxError):
        return []

In [31]:
df["crew"] = df["crew"].apply(extract_director)

In [32]:
df["tags"] = (
    df["overview"].fillna("")
    + " "
    + df["genres"].apply(lambda x: " ".join(x))
    + " "
    + df["keywords"].apply(lambda x: " ".join(x))
    + " "
    + df["cast"].apply(lambda x: " ".join(x))
    + " "
    + df["crew"].apply(lambda x: " ".join(x))
)

In [33]:
display(
    df[["title", "tags"]].head(10)
)

,title,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."
5,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...
6,Tangled,When the kingdom's most wanted-and most charmi...
7,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...
8,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he..."
9,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...

In [34]:
df["tags"] = (
    df["tags"]
    .str.lower()
    .str.replace(r"[^a-z0-9\s]", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [35]:
display(df[["title", "tags"]].head())

,title,tags
0,Avatar,in the 22nd century a paraplegic marine is dis...
1,Pirates of the Caribbean: At World's End,captain barbossa long believed to be dead has ...
2,Spectre,a cryptic message from bond s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,john carter is a war weary former military cap...

In [36]:
MODEL_DATA_PATH = (
    BASE_DIR
    / "data"
    / "processed"
    / "movies_features.csv"
)

df.to_csv(
    MODEL_DATA_PATH,
    index=False
)

print("✅ Feature dataset saved")
print(MODEL_DATA_PATH)
print("Dimensions :", df.shape)

✅ Feature dataset saved
c:\Users\Win 10\Desktop\movie-recommender\data\processed\movies_features.csv
Dimensions : (4803, 11)

In [37]:
display(df[["title", "genres", "keywords", "cast", "crew", "tags"]].head(5))

,title,genres,keywords,cast,crew,tags
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],in the 22nd century a paraplegic marine is dis...
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],captain barbossa long believed to be dead has ...
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],a cryptic message from bond s past sends him o...
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],following the death of district attorney harve...
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],john carter is a war weary former military cap...

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

In [40]:
tfidf_matrix = tfidf.fit_transform(
    df["tags"]
)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (4803, 5000)

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (4803, 4803)

In [43]:
indices = pd.Series(
    df.index,
    index=df["title"]
).drop_duplicates()

In [44]:
def recommend_movies(title, n=10):
    if title not in indices:
        return f"Movie '{title}' not found."

    idx = indices[title]

    similarity_scores = list(
        enumerate(similarity_matrix[idx])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:n + 1]

    movie_indices = [
        index
        for index, score in similarity_scores
    ]

    return df.iloc[movie_indices][
        ["title", "vote_average", "popularity"]
    ]

In [45]:
recommend_movies("Avatar")

                   title  vote_average  popularity
2403              Aliens           7.7   67.660940
3158               Alien           7.9   94.184658
1531           Moonraker           5.9   29.887404
838               Alien³           6.2   45.856409
4332      Silent Running           6.3   11.095414
2015          Spaceballs           6.7   39.890798
461        Lost in Space           5.0   17.455024
373      Mission to Mars           5.7   16.058284
2198             Lockout           5.8   35.232278
278   Planet of the Apes           5.6   51.188633

In [46]:
recommend_movies("The Dark Knight Rises")

                                        title  vote_average  popularity
65                            The Dark Knight           8.2  187.322927
428                            Batman Returns           6.6   59.113174
119                             Batman Begins           7.5  115.040024
1359                                   Batman           7.0   44.104469
299                            Batman Forever           5.2   48.205606
210                            Batman & Robin           4.2   50.073575
9          Batman v Superman: Dawn of Justice           5.7  155.790452
3854  Batman: The Dark Knight Returns, Part 2           7.9   25.891466
3819                                 Defendor           6.5    8.453420
879                       Law Abiding Citizen           7.2   49.593978

In [47]:
recommend_movies("Spectre")

                                title  vote_average  popularity
11                  Quantum of Solace           6.1  107.928811
29                            Skyfall           6.9   93.004993
1343            Never Say Never Again           5.8   23.380757
4071            From Russia with Love           6.9   41.298723
3285                         Restless           4.9    0.812776
4339                           Dr. No           6.9   48.901542
3251  On Her Majesty's Secret Service           6.5   25.289665
147                   Die Another Day           5.8   54.159392
3162                      Thunderball           6.5   31.036000
3143              You Only Live Twice           6.5   28.675891

In [48]:
recommend_movies("John Carter")

                        title  vote_average  popularity
373           Mission to Mars           5.7   16.058284
270               The Martian           7.6  167.932870
1735           Ghosts of Mars           4.8   13.145205
487                Red Planet           5.4   13.800656
473             Mars Attacks!           6.1   44.090535
0                      Avatar           7.2  150.437577
3668            Capricorn One           6.4   11.095219
278        Planet of the Apes           5.6   51.188633
581   Star Trek: Insurrection           6.3   19.711951
1341     The Inhabited Island           5.3    2.785832

In [49]:
def recommend_movies(title, n=10):
    if title not in indices:
        return f"Movie '{title}' not found."

    idx = indices[title]

    similarity_scores = list(
        enumerate(similarity_matrix[idx])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:n + 1]

    recommendations = []

    for movie_idx, score in similarity_scores:
        recommendations.append({
            "title": df.iloc[movie_idx]["title"],
            "similarity_score": round(float(score), 4),
            "vote_average": df.iloc[movie_idx]["vote_average"],
            "popularity": df.iloc[movie_idx]["popularity"],
        })

    return pd.DataFrame(recommendations)

In [50]:
recommend_movies("Avatar")

                title  similarity_score  vote_average  popularity
0              Aliens            0.4296           7.7   67.660940
1               Alien            0.3632           7.9   94.184658
2           Moonraker            0.3542           5.9   29.887404
3              Alien³            0.3473           6.2   45.856409
4      Silent Running            0.3151           6.3   11.095414
5          Spaceballs            0.3032           6.7   39.890798
6       Lost in Space            0.2935           5.0   17.455024
7     Mission to Mars            0.2845           5.7   16.058284
8             Lockout            0.2748           5.8   35.232278
9  Planet of the Apes            0.2717           5.6   51.188633

In [51]:
def recommend_movies(title, n=10):
    if title not in indices:
        return f"Movie '{title}' not found."

    idx = indices[title]

    similarity_scores = list(
        enumerate(similarity_matrix[idx])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    # Remove the movie itself
    similarity_scores = similarity_scores[1:n + 1]

    recommendations = []

    for movie_idx, score in similarity_scores:
        recommendations.append({
            "title": df.iloc[movie_idx]["title"],
            "similarity_score": round(float(score), 4),
            "vote_average": df.iloc[movie_idx]["vote_average"],
            "popularity": df.iloc[movie_idx]["popularity"],
        })

    return pd.DataFrame(recommendations)

In [52]:
recommend_movies("Avatar")

                title  similarity_score  vote_average  popularity
0              Aliens            0.4296           7.7   67.660940
1               Alien            0.3632           7.9   94.184658
2           Moonraker            0.3542           5.9   29.887404
3              Alien³            0.3473           6.2   45.856409
4      Silent Running            0.3151           6.3   11.095414
5          Spaceballs            0.3032           6.7   39.890798
6       Lost in Space            0.2935           5.0   17.455024
7     Mission to Mars            0.2845           5.7   16.058284
8             Lockout            0.2748           5.8   35.232278
9  Planet of the Apes            0.2717           5.6   51.188633

In [53]:
recommend_movies("The Dark Knight Rises")

,title,similarity_score,vote_average,popularity
0,The Dark Knight,0.5060,8.2,187.322927
1,Batman Returns,0.4291,6.6,59.113174
2,Batman Begins,0.4277,7.5,115.040024
3,Batman,0.3967,7.0,44.104469
4,Batman Forever,0.3743,5.2,48.205606
5,Batman & Robin,0.3104,4.2,50.073575
6,Batman v Superman: Dawn of Justice,0.2603,5.7,155.790452
7,"Batman: The Dark Knight Returns, Part 2",0.2280,7.9,25.891466
8,Defendor,0.1724,6.5,8.453420
9,Law Abiding Citizen,0.1436,7.2,49.593978

In [54]:
recommend_movies("Spectre")

                             title  similarity_score  vote_average  popularity
0                Quantum of Solace            0.3493           6.1  107.928811
1                          Skyfall            0.3386           6.9   93.004993
2            Never Say Never Again            0.3294           5.8   23.380757
3            From Russia with Love            0.3215           6.9   41.298723
4                         Restless            0.3188           4.9    0.812776
5                           Dr. No            0.2989           6.9   48.901542
6  On Her Majesty's Secret Service            0.2899           6.5   25.289665
7                  Die Another Day            0.2890           5.8   54.159392
8                      Thunderball            0.2889           6.5   31.036000
9              You Only Live Twice            0.2881           6.5   28.675891

In [55]:
import joblib

MODEL_DIR = BASE_DIR / "models"
MODEL_DIR.mkdir(exist_ok=True)

joblib.dump(
    tfidf,
    MODEL_DIR / "tfidf_vectorizer.joblib"
)

joblib.dump(
    similarity_matrix,
    MODEL_DIR / "similarity_matrix.joblib"
)

joblib.dump(
    indices,
    MODEL_DIR / "movie_indices.joblib"
)

print("✅ Content-based model artifacts saved")

✅ Content-based model artifacts saved

In [56]:
recommend_movies("Avatar")

                title  similarity_score  vote_average  popularity
0              Aliens            0.4296           7.7   67.660940
1               Alien            0.3632           7.9   94.184658
2           Moonraker            0.3542           5.9   29.887404
3              Alien³            0.3473           6.2   45.856409
4      Silent Running            0.3151           6.3   11.095414
5          Spaceballs            0.3032           6.7   39.890798
6       Lost in Space            0.2935           5.0   17.455024
7     Mission to Mars            0.2845           5.7   16.058284
8             Lockout            0.2748           5.8   35.232278
9  Planet of the Apes            0.2717           5.6   51.188633

In [57]:
RATINGS_PATH = BASE_DIR / "data" / "raw" / "ratings.csv"

ratings = pd.read_csv(RATINGS_PATH)

print("Ratings shape:", ratings.shape)
display(ratings.head())

Ratings shape: (100836, 4)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [58]:
print(ratings.columns.tolist())

['userId', 'movieId', 'rating', 'timestamp']

In [59]:
RATINGS_PATH = BASE_DIR / "data" / "raw" / "ratings.csv"

ratings = pd.read_csv(RATINGS_PATH)

print("Ratings shape:", ratings.shape)
display(ratings.head())

Ratings shape: (100836, 4)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [60]:
print(ratings.columns.tolist())

['userId', 'movieId', 'rating', 'timestamp']

In [61]:
print("Users:", ratings["userId"].nunique())
print("Movies:", ratings["movieId"].nunique())
print("Ratings:", len(ratings))

Users: 610
Movies: 9724
Ratings: 100836

In [62]:
display(ratings.describe())

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [63]:
display(ratings.head())

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [64]:
print(ratings.columns.tolist())

print("Users:", ratings["userId"].nunique())
print("Movies:", ratings["movieId"].nunique())
print("Ratings:", len(ratings))

['userId', 'movieId', 'rating', 'timestamp']
Users: 610
Movies: 9724
Ratings: 100836

In [65]:
print(ratings.columns.tolist())
print("Users:", ratings["userId"].nunique())
print("Movies:", ratings["movieId"].nunique())
print("Ratings:", len(ratings))

['userId', 'movieId', 'rating', 'timestamp']
Users: 610
Movies: 9724
Ratings: 100836

In [66]:
LINKS_PATH = BASE_DIR / "data" / "raw" / "links.csv"

links = pd.read_csv(LINKS_PATH)

print("Links shape:", links.shape)
display(links.head())

Links shape: (9742, 3)

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [67]:
print(links.columns.tolist())

['movieId', 'imdbId', 'tmdbId']

In [68]:
print("MovieLens movie IDs:", ratings["movieId"].nunique())
print("MovieLens IDs with TMDB mapping:", links["movieId"].isin(ratings["movieId"]).sum())
print("TMDB IDs available:", links["tmdbId"].notna().sum())

MovieLens movie IDs: 9724
MovieLens IDs with TMDB mapping: 9724
TMDB IDs available: 9734

In [69]:
ratings_tmdb = ratings.merge(
    links[["movieId", "tmdbId"]],
    on="movieId",
    how="left"
)

print("Ratings with TMDB mapping:")
display(ratings_tmdb.head())

Ratings with TMDB mapping:

   userId  movieId  rating  timestamp   tmdbId
0       1        1     4.0  964982703    862.0
1       1        3     4.0  964981247  15602.0
2       1        6     4.0  964982224    949.0
3       1       47     5.0  964983815    807.0
4       1       50     5.0  964982931    629.0

In [70]:
LINKS_PATH = BASE_DIR / "data" / "raw" / "links.csv"

links = pd.read_csv(LINKS_PATH)

print("Links shape:", links.shape)
print("Columns:", links.columns.tolist())

display(links.head())

Links shape: (9742, 3)
Columns: ['movieId', 'imdbId', 'tmdbId']

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [71]:
print("MovieLens movie IDs:", ratings["movieId"].nunique())
print("MovieLens IDs in links:", links["movieId"].isin(ratings["movieId"]).sum())
print("TMDB IDs available:", links["tmdbId"].notna().sum())

MovieLens movie IDs: 9724
MovieLens IDs in links: 9724
TMDB IDs available: 9734

In [72]:
ratings_tmdb = ratings.merge(
    links[["movieId", "tmdbId"]],
    on="movieId",
    how="left"
)

print("Ratings:", len(ratings_tmdb))
print("Ratings with TMDB ID:", ratings_tmdb["tmdbId"].notna().sum())
print("Ratings without TMDB ID:", ratings_tmdb["tmdbId"].isna().sum())

display(ratings_tmdb.head())

Ratings: 100836
Ratings with TMDB ID: 100823
Ratings without TMDB ID: 13

   userId  movieId  rating  timestamp   tmdbId
0       1        1     4.0  964982703    862.0
1       1        3     4.0  964981247  15602.0
2       1        6     4.0  964982224    949.0
3       1       47     5.0  964983815    807.0
4       1       50     5.0  964982931    629.0

In [73]:
ratings_tmdb = ratings_tmdb.dropna(subset=["tmdbId"]).copy()

ratings_tmdb["tmdbId"] = ratings_tmdb["tmdbId"].astype(int)

print("Usable ratings:", len(ratings_tmdb))
display(ratings_tmdb.head())

Usable ratings: 100823

   userId  movieId  rating  timestamp  tmdbId
0       1        1     4.0  964982703     862
1       1        3     4.0  964981247   15602
2       1        6     4.0  964982224     949
3       1       47     5.0  964983815     807
4       1       50     5.0  964982931     629

In [74]:
df["id"]

0        19995
1          285
2       206647
3        49026
4        49529
         ...
4798      9367
4799     72766
4800    231617
4801    126186
4802     25975
Name: id, Length: 4803, dtype: int64

In [75]:
tmdb_ids = set(df["id"])

ratings_tmdb = ratings_tmdb[
    ratings_tmdb["tmdbId"].isin(tmdb_ids)
].copy()

print("Ratings matching our TMDB 5000 catalog:", len(ratings_tmdb))
print("Movies matching our catalog:", ratings_tmdb["tmdbId"].nunique())

Ratings matching our TMDB 5000 catalog: 70194
Movies matching our catalog: 3535

In [76]:
from surprise import Dataset, Reader, SVD

In [77]:
svd_ratings = ratings_tmdb[
    ["userId", "tmdbId", "rating"]
].copy()

svd_ratings = svd_ratings.rename(
    columns={"tmdbId": "movieId"}
)

print("SVD dataset shape:", svd_ratings.shape)
display(svd_ratings.head())

SVD dataset shape: (70194, 3)

   userId  movieId  rating
0       1      862     4.0
3       1      807     5.0
4       1      629     5.0
5       1      755     3.0
6       1    13685     5.0

In [78]:
reader = Reader(
    rating_scale=(0.5, 5.0)
)

surprise_data = Dataset.load_from_df(
    svd_ratings[
        ["userId", "movieId", "rating"]
    ],
    reader
)

In [79]:
from surprise.model_selection import train_test_split

trainset, testset = train_test_split(
    surprise_data,
    test_size=0.2,
    random_state=42
)

print("Training ratings:", trainset.n_ratings)
print("Test ratings:", len(testset))

Training ratings: 56155
Test ratings: 14039

In [80]:
svd_model = SVD(
    n_factors=100,
    n_epochs=20,
    lr_all=0.005,
    reg_all=0.02,
    random_state=42
)

svd_model.fit(trainset)

print("✅ SVD model trained")

✅ SVD model trained

In [81]:
from surprise import accuracy

predictions = svd_model.test(testset)

rmse = accuracy.rmse(
    predictions,
    verbose=False
)

mae = accuracy.mae(
    predictions,
    verbose=False
)

print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mae:.4f}")

RMSE: 0.8484
MAE:  0.6504

In [82]:
user_id = 1
tmdb_movie_id = 19995  # Avatar

prediction = svd_model.predict(
    user_id,
    tmdb_movie_id
)

print(prediction)

user: 1          item: 19995      r_ui = None   est = 4.27   {'was_impossible': False}

In [83]:
def get_svd_recommendations(user_id, n=10):
    movie_ids = df["id"].tolist()

    predictions = []

    for movie_id in movie_ids:
        prediction = svd_model.predict(
            user_id,
            int(movie_id)
        )

        predictions.append({
            "movie_id": movie_id,
            "svd_score": prediction.est
        })

    recommendations = pd.DataFrame(predictions)

    recommendations = recommendations.sort_values(
        "svd_score",
        ascending=False
    ).head(n)

    recommendations = recommendations.merge(
        df[["id", "title", "vote_average", "popularity"]],
        left_on="movie_id",
        right_on="id",
        how="left"
    )

    return recommendations[
        ["movie_id", "title", "svd_score",
         "vote_average", "popularity"]
    ]

In [84]:
get_svd_recommendations(1, 10)

,movie_id,title,svd_score,vote_average,popularity
0,207,Dead Poets Society,5.0,8.1,55.458584
1,489,Good Will Hunting,5.0,7.9,43.734886
2,73,American History X,5.0,8.2,73.567232
3,68,Brazil,5.0,7.5,41.089863
4,429,"The Good, the Bad and the Ugly",5.0,8.1,88.377076
5,935,Dr. Strangelove or: How I Learned to Stop Worr...,5.0,8.0,41.996783
6,765,Evil Dead II,5.0,7.6,35.674774
7,2118,L.A. Confidential,5.0,7.7,24.860326
8,627,Trainspotting,5.0,7.8,63.513324
9,1891,The Empire Strikes Back,5.0,8.2,78.517830

In [85]:
def min_max_normalize(series):
    min_value = series.min()
    max_value = series.max()

    if max_value == min_value:
        return pd.Series(
            0.0,
            index=series.index
        )

    return (
        (series - min_value)
        / (max_value - min_value)
    )

In [86]:
def hybrid_recommend_movies(
    user_id,
    title,
    n=10,
    content_weight=0.6,
    collaborative_weight=0.4
):
    if title not in indices:
        return f"Movie '{title}' not found."

    movie_idx = indices[title]

    # Content-based similarity
    content_scores = similarity_matrix[movie_idx]

    content_df = pd.DataFrame({
        "movie_id": df["id"].values,
        "content_score": content_scores
    })

    # Collaborative predictions
    collaborative_scores = []

    for movie_id in df["id"]:
        prediction = svd_model.predict(
            user_id,
            int(movie_id)
        )

        collaborative_scores.append(
            prediction.est
        )

    content_df["collaborative_score"] = (
        collaborative_scores
    )

    # Normalize scores
    content_df["content_score"] = (
        min_max_normalize(
            content_df["content_score"]
        )
    )

    content_df["collaborative_score"] = (
        min_max_normalize(
            content_df["collaborative_score"]
        )
    )

    # Hybrid score
    content_df["hybrid_score"] = (
        content_weight
        * content_df["content_score"]
        +
        collaborative_weight
        * content_df["collaborative_score"]
    )

    # Remove selected movie
    content_df = content_df[
        content_df["movie_id"] != df.iloc[movie_idx]["id"]
    ]

    # Top recommendations
    recommendations = (
        content_df
        .sort_values(
            "hybrid_score",
            ascending=False
        )
        .head(n)
    )

    recommendations = recommendations.merge(
        df[
            ["id", "title",
             "vote_average",
             "popularity"]
        ],
        left_on="movie_id",
        right_on="id",
        how="left"
    )

    return recommendations[
        [
            "title",
            "hybrid_score",
            "content_score",
            "collaborative_score",
            "vote_average",
            "popularity"
        ]
    ]

In [87]:
hybrid_recommend_movies(
    user_id=1,
    title="Avatar",
    n=10
)

,title,hybrid_score,content_score,collaborative_score,vote_average,popularity
0,Aliens,0.574762,0.429577,0.792539,7.7,67.660940
1,Alien,0.528830,0.363226,0.777235,7.9,94.184658
2,The Thing,0.526084,0.243633,0.949762,7.8,52.731379
3,Gattaca,0.505372,0.227744,0.921814,7.5,70.398356
4,2001: A Space Odyssey,0.502794,0.245705,0.888427,7.9,86.201184
5,The Empire Strikes Back,0.491733,0.152888,1.000000,8.2,78.517830
6,The Right Stuff,0.461204,0.201548,0.850687,7.3,17.567332
7,Guardians of the Galaxy,0.457800,0.222508,0.810739,7.9,481.098624
8,Gravity,0.456034,0.245187,0.772304,7.3,110.153618
9,Serenity,0.453560,0.119500,0.954650,7.4,45.388937

In [88]:
import joblib

MODEL_DIR = BASE_DIR / "models"
MODEL_DIR.mkdir(exist_ok=True)

joblib.dump(
    svd_model,
    MODEL_DIR / "svd_model.joblib"
)

print("✅ SVD model saved")

✅ SVD model saved

In [89]:
df.to_pickle(
    BASE_DIR / "data" / "processed" / "movies_features.pkl"
)

print("✅ Movie features saved")

✅ Movie features saved